first try
Derzhko/HomeWork pull request #1
Opened 2019-10-07 19:17 UTC by Derzhko

2019-10-15 12:24 UTC, jzuken requested changes

2019-10-15 12:24 UTC, jzuken commented on hw3.2/main.c
> +    FILE *Kojima = fopen("/home/alxderzhko/HomeWork/hw3.2/kojimageniy.txt", "r");
у меня нет такого файла на диске. используй относительные пути, пожалуйста

2019-10-25 11:11 UTC, SpirinEgor requested changes

2019-10-25 11:11 UTC, SpirinEgor commented on hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
Теперь относительный путь неверный. Ты хоть пробовал это локально запустить? :disappointed:

2019-10-25 11:11 UTC, SpirinEgor commented on hw3.2/main.c
> +int main() {
Скобочка не там.

2019-10-27 20:26 UTC, Derzhko commented on hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
пробовал. У меня запускается, не могу найти проблему

2019-11-14 17:31 UTC, SpirinEgor commented on hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
Вообще обычно файл лежит рядом с исходником (как у тебя), поэтому и путь указывают `./file.txt`.
У тебя make собирает бинарники в отдельную папку, поэтому надо либо в `CMakeLists` копировать текстовый файл, либо у себя делать одно, но пушить другое (не очень хорошо).

2019-12-08 19:46 UTC, fefaleksey requested changes

2019-12-08 19:46 UTC, fefaleksey commented on hw3.2/main.c
> +        for (int i = 0; line[i] != '\n'; ++i)
Увы, но все не так просто и строки могут быть ооочень длинными (например длинной в 500 символов)

2019-12-17 13:11 UTC, SpirinEgor requested changes
[kojimageniy.txt](https://github.com/Derzhko/HomeWork/files/3973405/kojimageniy.txt)
Вот для этого файла у меня вывело 6 не пустых строк, а правильно 9

2019-12-17 16:16 UTC, Derzhko commented
не нашёл ошибки, программа же ищет количество непустых строк, да?

2019-12-20 12:10 UTC, SpirinEgor commented
Ой, мой косяк
почему-то смотрел на количество пустых строк)

2019-12-20 12:15 UTC, SpirinEgor requested changes

2019-12-20 12:15 UTC, SpirinEgor commented on hw3/hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
У тебя по-прежнему не туда ссылка стоит

2019-12-20 12:51 UTC, Derzhko commented on hw3/hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
В CmakeFile нужно указывать файл текста?

2019-12-20 12:55 UTC, Derzhko commented on hw3/hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
не понимаю почему, но при ссылке на файл ./file.txt он не хочет открываться, хотя лежит рядом с мейном

2019-12-20 19:54 UTC, SpirinEgor commented on hw3/hw3.2/main.c
> +    FILE *Kojima = fopen("../kojimageniy.txt", "r");
В CMakeList.txt надо написать `configure_file(filename filename COPYONLY)`, вместо `filename` нужный файл подставляешь. В таком случае у тебя этот файл скопируется в рабочую директорию

2019-12-22 05:59 UTC, merged