hw4.1
Derzhko/HomeWork pull request #12
Opened 2019-10-23 16:39 UTC by Derzhko

2019-11-14 17:12 UTC, SpirinEgor requested changes

2019-11-14 17:12 UTC, SpirinEgor commented on hw4.1/CircularList.c
> +// Created by Администратор on 20.10.2019.
Хех, разные задачи -- разные пользователи
Также спасибо, за информативный коммент, буду знать, что файл создал админ)

2019-11-14 17:12 UTC, SpirinEgor commented on hw4.1/CircularList.h
> +#ifndef HW4_1_LIST_H
Думаю, что `LIST_H` будет лучше, всё-таки реализация листа не зависит от задания

2019-11-14 17:12 UTC, SpirinEgor commented on hw4.1/CircularList.c
> +        newElement->position = ++list->last->position;
Лучше разделять несколько выражений

2019-11-14 17:12 UTC, SpirinEgor commented on hw4.1/CircularList.c
> +int size(List* list)
Можно добавить поле в `struct List`, изначально 0, при добавлении увеличивать на 1, при удалении уменьшать на 1, тогда в функции надо будет просто вернуть это значение.

2019-11-14 17:12 UTC, SpirinEgor commented on hw4.1/main.c
> +    printf("Insert number of soldiery\n");
soldiers

2019-11-21 11:11 UTC, SpirinEgor commented on hw4.1/main.c
> +int main() {
:disappointed:

2019-12-10 13:18 UTC, jzuken commented
а тут тоже нужна нормальная структура каталогов. поправь это во всех задачах, пожалуйста

2019-12-17 13:27 UTC, SpirinEgor requested changes

2019-12-17 13:27 UTC, SpirinEgor commented on hw4/hw4.1/CircularList.c
> +    List* newList = malloc(sizeof(List));
Вот здесь память утекает.
Ещё есть ошибки при обращение и записи.
Проверь валгриндом

2019-12-23 21:26 UTC, merged