hw6.1
Derzhko/HomeWork pull request #22
Opened 2019-11-27 19:19 UTC by Derzhko

2019-12-08 16:40 UTC, jzuken requested changes

2019-12-08 16:40 UTC, jzuken commented on hw6.1/main.c
> +int main()
definitely lost: 8 bytes in 1 blocks

2019-12-08 16:40 UTC, jzuken commented on hw6.1/main.c
> +    printf("Insert number\n");
Insert number
0
Number in exponential form
+1.000000*2^-1023

2019-12-19 11:36 UTC, SpirinEgor requested changes

2019-12-19 11:36 UTC, SpirinEgor commented on hw6/hw6.1/main.c
> +    unsigned char *numberInBinaryCode = malloc(sizeof(double));
Всё равно валгринд ругается

2019-12-23 21:28 UTC, merged