first try 2.5
Derzhko/HomeWork pull request #4
Opened 2019-10-07 19:58 UTC by Derzhko

2019-10-14 10:57 UTC, SpirinEgor requested changes

2019-10-14 10:57 UTC, SpirinEgor commented on hw2.5/main.c
> +}] - 'a'] != 0)
Неожиданно...

2019-10-14 10:57 UTC, SpirinEgor commented on hw2.5/main.c
> +    int asciiTableCode[asciiTableCodeLength];
Ну это не ascii таблица, так как ты нормируешь + хранится в массиве количество каждого символа, так что лучше назвать `charCounter` или что-то в этом духе.

2019-10-25 10:01 UTC, SpirinEgor requested changes
Не верный ответ для теста:
```
abcabc
abc
```

2019-10-27 20:06 UTC, Derzhko commented
> Не верный ответ для теста:
> 
> ```
> abcabc
> abc
> ```

Я правильно понял, заданием нужно было реализовать игру, где из букв исходного слова составлялись новые слова? или у нужно именно создавать новые слова с помощью перестановок, в результате получая слова той же длины, что и первоначальное?

2019-11-19 11:01 UTC, SpirinEgor commented
> > Не верный ответ для теста:
> > ```
> > abcabc
> > abc
> > ```
> 
> Я правильно понял, заданием нужно было реализовать игру, где из букв исходного слова составлялись новые слова? или у нужно именно создавать новые слова с помощью перестановок, в результате получая слова той же длины, что и первоначальное?

Нет, нужно проверить для 2 строк, что одно может быть получено из другого путём перестановки букв, например, для `abcabc` и `cabbac` это свойство выполняется, а для `abcc` и `abbc` нет

2019-12-10 12:54 UTC, merged