first try 3.1
Derzhko/HomeWork pull request #6
Opened 2019-10-07 20:14 UTC by Derzhko

2019-10-15 12:25 UTC, jzuken requested changes

2019-10-15 12:25 UTC, jzuken commented on hw3.1/main.c
> +                    if (numbers[2 * index + 1] > numbers[2 * index + 2])
вот эти индексы тут имеют вполне конкретное значение. давай сохраним их в константы с хорошими именами

2019-10-30 09:33 UTC, SpirinEgor requested changes

2019-10-30 09:33 UTC, SpirinEgor commented on hw3.1/main.c
> +void heapsort(int numbers[], int numbersLength)
Функция получилась очень большой, лучше всего её разбить на 2: в одной максимальный элемент будет всплывать наверх, а в другой вызываться первая функция, а затем рекурсивный запуск.

2019-11-20 12:00 UTC, SpirinEgor requested changes

2019-11-20 12:00 UTC, SpirinEgor commented on hw3.1/main.c
> +        return 0;
Вот тут лишний отступ

2019-12-10 11:00 UTC, merged