hw3.3
Derzhko/HomeWork pull request #9
Opened 2019-10-16 20:23 UTC by Derzhko

2019-10-25 11:18 UTC, SpirinEgor requested changes

2019-10-25 11:18 UTC, SpirinEgor commented on hw3.3/main.c
> +    int count = 0;
По сути эта переменная нужна, чтобы находить позицию, куда ставить 0, поэтому логичнее вместо того, чтобы вычислять каждый раз -- сразу хранить индекс.

2019-10-25 11:18 UTC, SpirinEgor commented on hw3.3/main.c
> +void endShift(int numbers[], int arrayLength)
Название можно и более говорящее.

2019-11-14 17:23 UTC, SpirinEgor requested changes

2019-11-14 17:23 UTC, SpirinEgor commented on hw3.3/main.c
> +int main() {
Скобка не на той строке

2019-11-14 17:23 UTC, SpirinEgor commented on hw3.3/main.c
> +void putEnd(int *numbers, int arrayLength)
Что-то не стало лучше)
`moveZerosToEnd`

2019-11-20 12:28 UTC, SpirinEgor commented on hw3.3/main.c
> +<<<<<<< HEAD
Так, у тебя какие-то конфликты при мердже, которые ты не разрешил.
Это надо поправить, если будут вопросы -- пиши в лс

2019-11-20 12:28 UTC, SpirinEgor commented on hw3.3/main.c
> +>>>>>>> 515ebcddb66052645d5ea8482e7af6661cc6aad1
И здесь конфликт

2019-12-10 11:11 UTC, jzuken requested changes

2019-12-10 11:11 UTC, jzuken commented on hw3.3/main.c
> +    int numbers[arrayMaxLength];
Insert length
6
Insert your numbers
3
7
0
4
0
1
Result array
3 7 1 4 0 0

2019-12-17 14:01 UTC, merged